#配置redis服务数据信息
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 600
        max-wait: 1000
        max-idle: 500
        min-idle: 100
    timeout: 2500
 #服务器端口
server:
  port: 8081